### ISSUE TITLE
patches are in "files" directory

### ISSUE THREAD

**Issue by kencu** [Traace/macports_fixes#1]
if you find some of your portfile mods are not working as expected, several (cmus, e.g.) are missing the patchfiles. MacPorts works slightly different than Homebrew. Small patches are usually included with the Portfile, in a directory called "files", eg <https://github.com/macports/macports-ports/blob/master/audio/cmus/>
```
Top_Level
|
-audio
   |
   cmus
      |
      Portfile
      files
          |
          patchfile1.diff
          patchfile2.diff

```
If you fix any Tiger-related things, please bring 'em forward and we'll include them in MacPorts. That's the other nice thing about MacPorts for older systems -- older systems are full members, and use (in most cases) all the latest port upgrades at the same time as all the other systems get them (if possible).

**Comment by Traace** [comment]
Hi kencu, 

I tried to include older patchfiles to the new version. However when I build it, I get a error complaining that patchfiles are missing. 

Even when building from offical macports repo it complains about patchfiles are missing. They should be located in files but that folder never exist.

Also I'm not sure if the newest version still needs the patches at all? Because its working fine for me.

I would like to publish portfiles and I'm aware of macports offical repo, but first my portfiles need more testing. Also I need to get known how to include checks " if darwin 8 or 9" inside portfiles to make fixes more specific.

Can you teach me some?

**Comment by kencu** [comment]
I'm trying to guess how you might have a copy of the ports tree that doesn't contain any of the files directories, and I'm drawing a blank. If you git clone it or download it via zip file you get it all, including the files dirs. Macports installs the files dirs by default with it's rsync update method.

For your personal mods, you need your local repo as you have, and the top level folders have to be made manually as you did.

After that, I usually start out by copying the existng port directory like so:

cd myrepo
cd audio
cp -R 'port dir cmus' .

(note that should be a backtic but seems none on this iPad)

**Comment by Traace** [comment]
Yes, I did the stock rsync method. But I might need to run a selfupdate again. If it fix it, great! . If not, I just grab them in zip.

Tomorrow I updated the portfiles with its proper patches. Thanks for your help.

**Comment by kencu** [comment]
If you do something like this:

cd `port dir cmus` 

it should take you right into the ports tree where cmus exists. Then if you `ls` you should see a files directory with some patches in it.

MacPorts first looks for patches in the files dir, then if they are not there, at the URL for master_sites.

**Comment by kencu** [comment]
hey, github took off my backtics again, around 

port dir cmus

**Comment by Traace** [comment]
We could also use "pwn" afterwards to see the exact location.
 Then just copy&paste location in finder, access the files and profit. Btw, patches restored to my cmus portfile.

Thanks again.
